added verification of info about the current user
store-challenge/store-app pull request #24
Opened 2023-07-03 14:21 UTC by halyna-k

2023-07-03 18:45 UTC, dimalian commented
You need to make a small refactor because your authorization structure is wrong.
1. You need to rename `AuthProvider` to `Auth0Provider` and wrap it around not only the `HeaderButton` but the whole app like this:
`<Auth0Privder> <App/></Auth0Provider>`
2. You need to create `AuthProvider.js `and get the token as you did in the file `Authentication.js` and put it to the Axios client like this:
  ```
    useEffect(() => {
        authData
          .getAccessTokenSilently({
            authorizationParams: {
              audience, // Value in Identifier field for the API being called.
            },
          })
          .then(token => axiosClient.interceptors.request.use((config) => {
            config.headers.Authorization = `Bearer ${token}`;
          }))
          .catch(error => console.log(error));
      }, [audience, authData])
```
and wrap the `App` with this provider: 

```
<Auth0Privder>
  <AuthPrivder>
     <App/>
  </AuthPrivder>
</Auth0Provider>
```
4. Put all these providers in the separate folder `providers` inside the `src` folder

2023-07-03 18:46 UTC, dimalian requested changes

2023-07-03 18:46 UTC, dimalian commented on src/components/Authentication/Authentication.js
> +      const getUserMetaData = async () => {
The data for the user profile must be obtained from the back-end. Profile data will not always be the same as the data from auth0.

2023-07-03 18:46 UTC, dimalian commented on src/components/Authentication/Authentication.js
> +           });
You need to get this token and put it to the Axios config.
You can do it in this way `axiosClient.interceptors.request.use((config) => {
        config.headers.Authorization = `Bearer ${token}``

2023-07-05 20:45 UTC, dimalian requested changes

2023-07-05 20:45 UTC, dimalian commented on src/providers/AuthProvider.js
> +           console.log(token);
Remove it

2023-07-05 20:45 UTC, dimalian commented on .vscode/settings.json
Add this folder to the gitignore. Not everyone uses vscode

2023-07-05 20:47 UTC, halyna-k commented on .vscode/settings.json
Okay

2023-07-05 21:00 UTC, merged