added category list extension
store-challenge/store-app pull request #26
Opened 2023-07-03 22:17 UTC by halyna-k

2023-07-04 16:18 UTC, djek195 approved these changes

2023-07-04 18:44 UTC, dimalian requested changes

2023-07-04 18:44 UTC, dimalian commented on src/components/CategoryList/CategoryList.js
> +    xlColumns,
The component should be responsible for the correct display on different devices. You must choose the size of the columns and the spacing within the component.

2023-07-04 18:44 UTC, dimalian commented on src/components/CategoryList/CategoryList.js
> +    array,
rename to categories

2023-07-04 18:44 UTC, dimalian commented on src/components/CategoryList/CategoryList.js
> +      {Array.from(array).map((el, index) => (
Why not just write
```suggestion
      {array.map((el, index) => (
```

2023-07-04 18:44 UTC, dimalian commented on src/components/CategoryList/CategoryList.js
> +        <Grid key={index} xs={xsColumns} sm={smColumns} md={mdColumns} xl={xlColumns}>
If you have a unique value in the array, put it into the key parameter and avoid using the index. 
```suggestion
        <Grid key={el.name} xs={xsColumns} sm={smColumns} md={mdColumns} xl={xlColumns}>
```

2023-07-04 18:44 UTC, dimalian commented on src/pages/CatalogPage/CatalogPage.js
> +  const sm = useMediaQuery('(min-width: 480px)');
This option is more readable and has less chance to make a mistake.
```suggestion
  const sm = useMediaQuery(theme.breakpoints.up('sm'));
```

2023-07-04 18:44 UTC, dimalian commented on src/pages/CatalogPage/CatalogPage.js
> +            <CategoryMoreButton text={buttonText} onClick={handleClickShowMore} />
```suggestion
            <CategoryMoreButton text={showMore ? 'Більше категорій' : 'Зменшити'} onClick={handleClickShowMore} />
```

2023-07-04 18:44 UTC, dimalian commented on src/pages/CatalogPage/CatalogPage.js
> +            onClick={handleClickCategoryButton} />
All these conditions must be inside the CategoryList component. The parent component mustn't be worried about how to show the component on the different screens.

2023-07-05 21:17 UTC, dimalian requested changes

2023-07-05 21:17 UTC, dimalian commented on src/components/Advertising/Advertising.js
> +  }, [randomNumber]);
```suggestion
  useEffect(() => {
    const randomNumber = (Math.floor(Math.random() * 
  images.length));
      setCurrentImage(randomNumber);
  }, []);
```

2023-07-05 21:17 UTC, dimalian commented on src/components/CategoryList/CategoryList.js
> +    array,
this comment wasn't resolved

2023-07-05 21:17 UTC, dimalian commented on src/components/CategoryList/CategoryListMobile.js
> +  const [buttonText, setButtonText] = useState('Більше категорій');
Don't create unnecessary useState. Show specific text according to the showMore variable.

2023-07-05 21:17 UTC, dimalian commented on src/components/CategoryList/CategoryListMobile.js
> +        <CategoryMoreButton text={buttonText} onClick={handleClickShowMore} />
```suggestion
        <CategoryMoreButton text={showMore ? 'more' : 'less'} onClick={handleClickShowMore} />
```

2023-07-05 22:30 UTC, dimalian approved these changes

2023-07-06 10:40 UTC, merged